### ISSUE TITLE
Query mangled

### ISSUE THREAD

**Issue by thomasbhatia** [epuzanov/ZenPacks.community.SQLDataSource#1]
The query entered in Data Source is not the same when data source is actually executed.

Example:

Test Data Source:
Preparing Command...
Executing query: "SELECT sum(count) as TotalCalls FROM `data_raw` WHERE originate='13099'"
Results:
TotalCalls
339554
DONE in 0 seconds

And this is from zenperfsql.log:
2012-06-26 18:16:34,584 DEBUG zen.collector.scheduler: Task localhost 60 7746113250253126100 finished, result: [(SELECT sum(count) as TotalCalls,originate FROM `data_raw`, ParsedResults
  events: [{'component': 'localhost',
  'device': 'localhost',
  'eventClass': '/Status',
  'eventKey': 'SS7',
  'severity': 0,
  'summary': 'Datasource Device/SS7 query completed successfully'}]
  values: [(TotalCalls:totalcalls, None)]})]

**Comment by epuzanov** [comment]
it's not a bug it's a feature.
SQLDataSource tried to optimize SQL requests (merge multiple requests in single one). I think, in your case, results can not be parsed correctly, because 'originate' value returned as float. So you have two options:
1. disable request optimization by adding "LIMIT" or  "OR" to your WHERE clause (o.e. "SELECT sum(count) as TotalCalls FROM data_raw WHERE originate='13099' LIMIT 1"  or "SELECT sum(count) as TotalCalls FROM data_raw WHERE originate='13099' OR originate='13099'")
2. cast originate as int or string type (o.e "SELECT sum(count) as TotalCalls, cast(cast(originate as int) as string) as originate FROM data_raw WHERE originate='13099'")

**Comment by thomasbhatia** [comment]
Thank you very much for taking the time to explain.
